const currency=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});const colors=['#2563eb','#06b6d4','#7c3aed','#16a34a','#f97316','#dc2626','#0ea5e9','#84cc16','#f59e0b','#64748b'];let data;
async function init(){const r=await fetch('../azure-finops-poc/data/azure_cost.json',{cache:'no-store'});data=await r.json();safeData();set('lastUpdated',data.generatedAt||'-');set('sourceBlob',data.sourceBlob?`Source: ${data.sourceBlob}`:'');fill('subscriptionFilter',data.costBySubscription);fill('serviceFilter',data.costByService);fill('resourceGroupFilter',data.costByResourceGroup);['subscriptionFilter','serviceFilter','resourceGroupFilter','resourceSearch'].forEach(id=>$(id).addEventListener('input',render));$('resetFilters').onclick=()=>{subscriptionFilter.value='all';serviceFilter.value='all';resourceGroupFilter.value='all';resourceSearch.value='';render()};$('exportJson').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='azure_finops_v2_data.json';a.click()};render()}
function safeData(){data.summary=data.summary||{};['costBySubscription','costByService','costByResourceGroup','costByRegion','dailyTrend','topResources'].forEach(k=>data[k]=data[k]||[])}
function fill(id,rows){const s=$(id);(rows||[]).slice(0,150).forEach(r=>{let o=document.createElement('option');o.value=r.name;o.textContent=r.name;s.appendChild(o)})}
function filtered(){const sub=subscriptionFilter.value,svc=serviceFilter.value,rg=resourceGroupFilter.value,q=resourceSearch.value.toLowerCase();return(data.topResources||[]).filter(r=>(sub==='all'||r.subscriptionName===sub)&&(svc==='all'||r.service===svc)&&(rg==='all'||r.resourceGroup===rg)&&(!q||`${r.resourceName||''} ${r.resourceId||''}`.toLowerCase().includes(q)))}
function render(){const active=subscriptionFilter.value!=='all'||serviceFilter.value!=='all'||resourceGroupFilter.value!=='all'||resourceSearch.value;const fr=filtered();const total=active?sum(fr.map(x=>x.cost)):data.summary.totalCost||0;const avg=avgNum((data.dailyTrend||[]).map(x=>x.cost||0));const high=(data.dailyTrend||[]).reduce((a,b)=>(b.cost||0)>(a.cost||0)?b:a,{date:'-',cost:0});set('totalCost',currency.format(total));set('subscriptionCount',data.summary.subscriptionCount||0);set('resourceGroupCount',data.summary.resourceGroupCount||0);set('resourceCount',data.summary.resourceCount||0);set('avgDailyCost',currency.format(avg));set('monthlyRunRate',currency.format(avg*30));set('topSubscription',top(data.costBySubscription));set('topService',top(data.costByService));set('topResourceGroup',top(data.costByResourceGroup));set('highestDay',`${high.date} / ${currency.format(high.cost||0)}`);bars('subscriptionChart',data.costBySubscription);bars('serviceChart',data.costByService);bars('resourceGroupChart',data.costByResourceGroup);bars('regionChart',data.costByRegion);trend('dailyTrendChart',data.dailyTrend);table(active?fr:data.topResources)}
function bars(id,rows){const el=$(id),items=(rows||[]).filter(x=>x&&x.cost>0).slice(0,12);if(!items.length){el.innerHTML='<div class="empty">No data available</div>';return}const max=Math.max(...items.map(x=>x.cost));el.innerHTML=items.map((r,i)=>`<div class="barRow"><div class="barLabel" title="${esc(r.name)}">${esc(r.name||'Unassigned')}</div><div class="barTrack"><div class="barFill" style="width:${Math.max((r.cost/max)*100,4)}%;background:${colors[i%colors.length]}"></div></div><div class="barValue">${currency.format(r.cost)}</div></div>`).join('')}
function trend(id,rows){const el=$(id),items=(rows||[]).filter(x=>x&&x.cost>0);if(!items.length){el.innerHTML='<div class="empty">No trend data available</div>';return}const max=Math.max(...items.map(x=>x.cost));el.innerHTML=items.map(x=>`<div class="trendCol"><div class="trendValue">${currency.format(x.cost)}</div><div class="trendBar" style="height:${Math.max((x.cost/max)*210,14)}px"></div><div class="trendLabel">${esc(x.date)}</div></div>`).join('')}
function table(rows){const list=(rows||[]).slice(0,25);set('tableInfo',`${list.length} rows shown`);$('topResources').innerHTML=list.map(r=>`<tr><td>${esc(r.resourceName||r.resourceId||'Unknown')}</td><td><span class="pill">${esc(r.subscriptionName||'')}</span></td><td>${esc(r.resourceGroup||'')}</td><td>${esc(r.service||'')}</td><td>${currency.format(r.cost||0)}</td></tr>`).join('')}
function top(rows){let r=(rows||[])[0];return r?`${r.name} (${currency.format(r.cost||0)})`:'-'}function sum(a){return a.reduce((x,y)=>x+(y||0),0)}function avgNum(a){return a.length?sum(a)/a.length:0}function $(id){return document.getElementById(id)}function set(id,v){let e=$(id);if(e)e.textContent=v}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}init().catch(e=>{console.error(e);set('lastUpdated','Failed to load data')});